"""
NEXUS Execution Agent
Autonomously executes action items: Slack messages, Jira tickets, email.
All integrations are optional — falls back to logging if keys not present.
"""
import json
import httpx
from datetime import datetime, timedelta
from backend.config import (
    SLACK_WEBHOOK_URL, JIRA_BASE_URL, JIRA_API_TOKEN,
    JIRA_USER_EMAIL, slack_enabled, jira_enabled
)


class ExecutionAgent:
    """
    Executes a single action item. Returns a result dict with:
      - action: the original item
      - channel: which integration was used (slack / jira / email / logged)
      - status: success / failed / simulated
      - detail: human-readable outcome
    """

    async def execute(self, action: str, domain: str, analysis: str) -> dict:
        """Route action to the best available execution channel."""
        result = {"action": action, "domain": domain, "timestamp": datetime.utcnow().isoformat()}

        # Try Jira first for task-like actions
        if jira_enabled() and self._is_task_like(action):
            outcome = await self._create_jira_ticket(action, domain, analysis)
            return {**result, **outcome}

        # Try Slack for notifications and updates
        if slack_enabled():
            outcome = await self._send_slack_message(action, domain)
            return {**result, **outcome}

        # Fallback: log the action (simulated execution for demo)
        return {
            **result,
            "channel": "logged",
            "status":  "simulated",
            "detail":  f"Action recorded (no integrations configured): {action}",
        }

    # ── Slack ──────────────────────────────────────────────────────────────────

    async def _send_slack_message(self, action: str, domain: str) -> dict:
        emoji_map = {"legal": "⚖️", "finance": "💰", "hr": "👥", "ops": "⚙️", "general": "📋"}
        emoji = emoji_map.get(domain, "📋")
        payload = {
            "text": f"{emoji} *NEXUS Action Item* [{domain.upper()}]",
            "blocks": [
                {"type": "header",  "text": {"type": "plain_text", "text": f"{emoji} NEXUS Action Item"}},
                {"type": "section", "text": {"type": "mrkdwn",     "text": f"*Domain:* {domain.upper()}\n*Action:* {action}"}},
                {"type": "context", "elements": [{"type": "mrkdwn", "text": f"Generated by NEXUS · {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"}]},
            ],
        }
        try:
            async with httpx.AsyncClient(timeout=10) as client:
                resp = await client.post(SLACK_WEBHOOK_URL, json=payload)
                if resp.status_code == 200:
                    return {"channel": "slack", "status": "success", "detail": "Slack message sent"}
                return {"channel": "slack", "status": "failed", "detail": f"Slack HTTP {resp.status_code}"}
        except Exception as exc:
            return {"channel": "slack", "status": "failed", "detail": str(exc)}

    # ── Jira ───────────────────────────────────────────────────────────────────

    async def _create_jira_ticket(self, action: str, domain: str, analysis: str) -> dict:
        priority_map = {"legal": "High", "finance": "High", "hr": "Medium", "ops": "Medium", "general": "Low"}
        due_date = (datetime.utcnow() + timedelta(days=7)).strftime("%Y-%m-%d")

        # Try to extract owner from analysis JSON
        owner = self._extract_owner(analysis)

        payload = {
            "fields": {
                "project":     {"key": "NEXUS"},
                "summary":     action[:255],
                "description": {
                    "type":    "doc",
                    "version": 1,
                    "content": [{"type": "paragraph", "content": [
                        {"type": "text", "text": f"Domain: {domain.upper()}\n\nGenerated by NEXUS from meeting transcript.\n\nOwner: {owner}"}
                    ]}],
                },
                "issuetype": {"name": "Task"},
                "priority":  {"name": priority_map.get(domain, "Medium")},
                "duedate":   due_date,
            }
        }
        try:
            auth = (JIRA_USER_EMAIL, JIRA_API_TOKEN)
            headers = {"Content-Type": "application/json"}
            async with httpx.AsyncClient(timeout=15, auth=auth) as client:
                resp = await client.post(
                    f"{JIRA_BASE_URL}/rest/api/3/issue",
                    json=payload, headers=headers
                )
                if resp.status_code in (200, 201):
                    key = resp.json().get("key", "?")
                    return {"channel": "jira", "status": "success", "detail": f"Jira ticket {key} created", "ticket_key": key}
                return {"channel": "jira", "status": "failed", "detail": f"Jira HTTP {resp.status_code}: {resp.text[:200]}"}
        except Exception as exc:
            return {"channel": "jira", "status": "failed", "detail": str(exc)}

    # ── Helpers ────────────────────────────────────────────────────────────────

    @staticmethod
    def _is_task_like(action: str) -> bool:
        task_words = ["review", "create", "prepare", "schedule", "update", "send", "complete",
                      "analyse", "analyze", "submit", "draft", "contact", "follow", "check"]
        return any(w in action.lower() for w in task_words)

    @staticmethod
    def _extract_owner(analysis_json: str) -> str:
        try:
            data = json.loads(analysis_json)
            actions = data.get("enriched_actions", [])
            if actions:
                return actions[0].get("owner", "Unassigned")
        except Exception:
            pass
        return "Unassigned"


    async def execute_batch(self, action_items: list[str], domain: str, analysis: str) -> list[dict]:
        """Execute multiple action items concurrently."""
        import asyncio
        tasks = [self.execute(item, domain, analysis) for item in action_items]
        return await asyncio.gather(*tasks)
