"""
NEXUS Execution Agent
Plugin-based: add any integration by adding a method.
All integrations gracefully degrade if not configured.
"""
import json, httpx
from datetime import datetime, timedelta
from backend.config import (
    SLACK_WEBHOOK_URL, JIRA_BASE_URL, JIRA_API_TOKEN, JIRA_USER_EMAIL,
    LINEAR_API_KEY, NOTION_API_KEY, WEBHOOK_URL,
    slack_enabled, jira_enabled, linear_enabled, notion_enabled, webhook_enabled
)


class ExecutionAgent:

    async def execute(self, action: str, domain: str, analysis: str) -> dict:
        base = {"action": action, "domain": domain, "timestamp": datetime.utcnow().isoformat()}

        # Try integrations in priority order
        if jira_enabled() and self._is_task(action):
            return {**base, **await self._jira(action, domain, analysis)}
        if linear_enabled() and self._is_task(action):
            return {**base, **await self._linear(action, domain)}
        if notion_enabled():
            return {**base, **await self._notion(action, domain)}
        if slack_enabled():
            return {**base, **await self._slack(action, domain)}
        if webhook_enabled():
            return {**base, **await self._webhook(action, domain, analysis)}

        # Fallback: log only (demo / self-hosted with no integrations)
        return {**base, "channel": "logged", "status": "simulated",
                "detail": f"Recorded (no integrations configured): {action}"}

    async def execute_batch(self, items: list[str], domain: str, analysis: str) -> list[dict]:
        import asyncio
        return await asyncio.gather(*[self.execute(i, domain, analysis) for i in items])

    # ── Slack ──────────────────────────────────────────────────────────────────
    async def _slack(self, action: str, domain: str) -> dict:
        icons = {"legal":"⚖️","finance":"💰","hr":"👥","ops":"⚙️","sales":"📈","marketing":"📣","general":"📋"}
        body  = {
            "text": f"{icons.get(domain,'📋')} *NEXUS Action* [{domain.upper()}]: {action}",
            "blocks": [
                {"type":"section","text":{"type":"mrkdwn","text":f"*{icons.get(domain,'📋')} NEXUS Action Item*\n*Domain:* {domain.upper()}\n*Task:* {action}"}},
                {"type":"context","elements":[{"type":"mrkdwn","text":f"Generated by NEXUS · {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"}]},
            ],
        }
        try:
            async with httpx.AsyncClient(timeout=10) as c:
                r = await c.post(SLACK_WEBHOOK_URL, json=body)
                return {"channel":"slack","status":"success" if r.status_code==200 else "failed","detail":f"HTTP {r.status_code}"}
        except Exception as e:
            return {"channel":"slack","status":"failed","detail":str(e)}

    # ── Jira ───────────────────────────────────────────────────────────────────
    async def _jira(self, action: str, domain: str, analysis: str) -> dict:
        prio = {"legal":"High","finance":"High","hr":"Medium","ops":"Medium","sales":"High","marketing":"Low","general":"Low"}
        due  = (datetime.utcnow() + timedelta(days=7)).strftime("%Y-%m-%d")
        body = {"fields": {
            "project":{"key":"NEXUS"},
            "summary": action[:255],
            "description":{"type":"doc","version":1,"content":[{"type":"paragraph","content":[{"type":"text","text":f"Domain: {domain}\n\nAuto-generated by NEXUS from meeting transcript."}]}]},
            "issuetype":{"name":"Task"}, "priority":{"name":prio.get(domain,"Medium")}, "duedate":due,
        }}
        try:
            async with httpx.AsyncClient(timeout=15, auth=(JIRA_USER_EMAIL, JIRA_API_TOKEN)) as c:
                r = await c.post(f"{JIRA_BASE_URL}/rest/api/3/issue", json=body, headers={"Content-Type":"application/json"})
                if r.status_code in (200,201):
                    return {"channel":"jira","status":"success","detail":f"Ticket {r.json().get('key')} created"}
                return {"channel":"jira","status":"failed","detail":f"HTTP {r.status_code}"}
        except Exception as e:
            return {"channel":"jira","status":"failed","detail":str(e)}

    # ── Linear ────────────────────────────────────────────────────────────────
    async def _linear(self, action: str, domain: str) -> dict:
        """Linear.app — popular with engineering/product teams."""
        query = """
        mutation CreateIssue($title: String!, $description: String) {
          issueCreate(input: {title: $title, description: $description}) {
            success
            issue { id identifier url }
          }
        }
        """
        try:
            async with httpx.AsyncClient(timeout=15, headers={"Authorization": LINEAR_API_KEY, "Content-Type":"application/json"}) as c:
                r = await c.post("https://api.linear.app/graphql", json={"query":query,"variables":{"title":action,"description":f"Domain: {domain}\nGenerated by NEXUS."}})
                data = r.json()
                if data.get("data",{}).get("issueCreate",{}).get("success"):
                    issue = data["data"]["issueCreate"]["issue"]
                    return {"channel":"linear","status":"success","detail":f"Issue {issue['identifier']} created","url":issue.get("url")}
                return {"channel":"linear","status":"failed","detail":str(data.get("errors"))}
        except Exception as e:
            return {"channel":"linear","status":"failed","detail":str(e)}

    # ── Notion ────────────────────────────────────────────────────────────────
    async def _notion(self, action: str, domain: str) -> dict:
        """Add action item as a page to a Notion database (set NOTION_DATABASE_ID)."""
        db_id = os.getenv("NOTION_DATABASE_ID", "")
        if not db_id:
            return {"channel":"notion","status":"failed","detail":"NOTION_DATABASE_ID not set"}
        body = {
            "parent": {"database_id": db_id},
            "properties": {
                "Name":   {"title": [{"text":{"content": action[:200]}}]},
                "Domain": {"select": {"name": domain.capitalize()}},
                "Status": {"select": {"name": "To Do"}},
            }
        }
        try:
            async with httpx.AsyncClient(timeout=15, headers={"Authorization":f"Bearer {NOTION_API_KEY}","Notion-Version":"2022-06-28","Content-Type":"application/json"}) as c:
                r = await c.post("https://api.notion.com/v1/pages", json=body)
                if r.status_code == 200:
                    return {"channel":"notion","status":"success","detail":f"Notion page created"}
                return {"channel":"notion","status":"failed","detail":f"HTTP {r.status_code}"}
        except Exception as e:
            return {"channel":"notion","status":"failed","detail":str(e)}

    # ── Generic Webhook (Zapier, Make, n8n, etc.) ─────────────────────────────
    async def _webhook(self, action: str, domain: str, analysis: str) -> dict:
        payload = {"action":action,"domain":domain,"analysis":analysis,"timestamp":datetime.utcnow().isoformat(),"source":"nexus"}
        try:
            async with httpx.AsyncClient(timeout=15) as c:
                r = await c.post(WEBHOOK_URL, json=payload)
                return {"channel":"webhook","status":"success" if r.status_code<400 else "failed","detail":f"HTTP {r.status_code}"}
        except Exception as e:
            return {"channel":"webhook","status":"failed","detail":str(e)}

    @staticmethod
    def _is_task(action: str) -> bool:
        verbs = ["review","create","prepare","schedule","update","send","complete","analyse",
                 "analyze","submit","draft","contact","follow","check","build","design","fix","deploy"]
        return any(v in action.lower() for v in verbs)


import os
